#!/usr/bin/perl

use Cow;
use Horse;
use Sheep;

# Cow::speak;
# Horse::speak;
# Sheep::speak;

my @pasture = qw(Cow Cow Horse Sheep Sheep);
foreach my $beast (@pasture) {
  # no strict 'refs';
  # &{$beast."::speak"};
  $beast->speak;
}
